### ISSUE TITLE
Add if/else logic for page elements

### ISSUE THREAD

**Issue by marlowpayne** [mobify/nightwatch-commands#24]
We could really use if/else logic functions for presence/visibility of page elements. This would allow us to set up tests with conditional checks and adjust the test accordingly. For example, to check whether a "Sold out"-type element is present, and divert an Add-to-cart flow to add a different, non-sold-out item.

Possible commands could be:
`ifElementExists(selector)`
`ifElementNotExists(selector)`
`ifElementVisible(selector)`
`ifElementHidden(selector)`

A possible test flow using a command could be of the form:
```
ifElementExists(selector) {
    do foo
} else {
    do bar
}
```

**Comment by QuantumInformation** [comment]
+1

**Comment by mobify-derrick** [comment]
This is probably too case specific to generalize into a custom command, the snippet above is what you should integrate into your tests.

**Comment by oubre** [comment]
I'm using code like @ellenmobify's example, but it's pretty messy when using page objects, and doesn't really integrate with the flow they're designed for. Being able to do something like:
```if(mypage.elements.myElem.is.present)```
instead of:
```this.element(
      'css selector',
      this.elements.myElem.selector,
      function(elem) {
        if(elem.status === -1) {
```

**Comment by danielburkewilliams** [comment]
Thanks.  Using this solution and it worked perfectly.  had a service that i was never sure would be on or not so checks to see if the element associated to that page is present or not. if it's not present - i move on to the next page. if it is present fill in the form and then hit the next page.

  //Executing Function. If statement to care for two pages/unsure if database will be down or not.
  client.flowWrapperNoContinueButton(function () {//waits for page to load
    client.waitForElementVisible('div[class="rightBox"]', 30000, function () {//waiting for green box which is on both pages
      client.element('css selector', 'div[class="boxContent"]>p', function(result){//statement checking if element is present
        if(result.value && result.value.ELEMENT) {//if element is present do this
          green_box.setValue('@first_name_input', 'Roger', function() {
            green_box.setValue('@last_name_input', 'Bannister', function () {
              green_box.setValue('@tel_number_input', '9194777863', function () {
                Webphone_SO_Failure_0010_Page.click('@continue_button', function () {
                  custom_testing();
                });
              });
            });
          });
        } else {
          custom_testing();
        }
      });
    });
  });

  return client;
}

**Comment by pakpaak** [comment]
@ellenmobify just try this and work perfectly, thanks! :)

**Comment by Ftelf** [comment]
That's nice, but how to use it using @ alias ?
