### ISSUE TITLE
Add Command waitForUrlToContain() command

### ISSUE THREAD

**Issue by mobify-derrick** [mobify/nightwatch-commands#43]
Expand on the waitForUrl command to allow for a URL to contain a specified value.

The waitForUrl command is limited to an exact match, we want a command to wait for url to contain a certain string, this is useful in cases where the URL might append a session hash or randomly generated token. ex 'http://www.mystore.com/checkout?123456789" we would want to wait for "http://www.mystore.com/checkout"

**Comment by ellenmobify** [comment]
Completed with https://github.com/mobify/nightwatch-commands/pull/46
