### ISSUE TITLE
Check for selenium-server.jar and chromedriver binary before downloading

### ISSUE THREAD

**Issue by ellenmobify** [mobify/nightwatch-commands#53]
### Summary

When installing nightwatch-commands, a copy of selenium-server.jar and a chromedriver binary are downloaded as well. If these files already exist, perhaps we don't need to redownload every time. 
### Expected behaviour

To save time and bandwidth, don't download selenium-server and chromedriver binary if they already exist locally.
### Actual behaviour

Download every time.
### Steps to reproduce
1. In `package.json`, use a different version of nightwatch-commands
2. `npm install`
3. selenium-server and chromedriver are downloaded even though a local copy of the same version already exists

**Comment by brettjonesdev** [comment]
You might check out [selenium-download](https://github.com/groupon/selenium-download) as it handles this exact scenario. May be worth using in this project instead of reinventing the wheel.
